# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe0328716b9e7bb5bcaa87b76e18be14"
name = "Tanami"
application_url = "https://tanami-leki-shopify-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,write_customers,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://tanami-leki-shopify-app.onrender.com/auth/callback",
  "https://tanami-leki-shopify-app.onrender.com/auth/shopify/callback",
  "https://tanami-leki-shopify-app.onrender.com/api/auth/callback",
]

[app_proxy]
url = "https://tanami-leki-shopify-app.onrender.com"
subpath = "leki"
prefix = "apps"
