APP_PASSWORD = "Golden1"
SUPABASE_URL = "https://acmueqibtcyggwvrboii.supabase.co"
SUPABASE_KEY = "sb_secret_eGk-gNGoINv3bJOYVXnQVg_MnbUDruS"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbXVlcWlidGN5Z2d3dnJib2lpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTMwNTU2OSwiZXhwIjoyMDgwODgxNTY5fQ.-MfF7dyCf6MQQzMQvvqRaQTifscemBZd9luMboBdWUs"